Sprint-8/homebanking/Login/urls.py
from django.contrib import admin
from django.urls import path
from Login import views

urlpatterns = [
    path('',views.LoginPackage.home,name="home"),
]

Sprint-8/homebanking/Prestamos/urls.py
from django.contrib import admin
from django.urls import path, include
from Prestamos import views
from rest_framework import routers
from . import views

router = routers.SimpleRouter()
router.register('API_Prestamos',views.PrestamosView,basename="API_Prestamos")
router.register('API_PrestamosAdmin',views.PrestamoEmpleado,basename="API_PrestamosAdmin")
urlpatterns = router.urls

urlpatterns += [
    path('Prestamos',views.PrestamoPackage.log_page,name="prestamos"),
    path('Prestamos/Mensaje/',views.PrestamoPackage.mensaje)

]

Sprint-8/homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login.urls')),
    path('Cuentas/',include('Cuentas.urls')),
    path('Cuentas/',include('Prestamos.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('Clientes/',include('Clientes.urls')),
    path('Tarjetas/',include('Tarjetas.urls'))
]

Sprint-8/homebanking/Cuentas/models.py
from django.db import models
from Clientes.models import Cliente

# Create your models here.
class Tipocuenta(models.Model):
    tcuenta_id = models.AutoField(db_column='TCuenta_id', primary_key=True)  # Field name made lowercase.
    tcuenta_tipo = models.TextField(db_column='TCuenta_tipo')  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'TipoCuenta'


class Cuenta(models.Model):
    account_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(Cliente,on_delete=models.CASCADE)
    balance = models.IntegerField()
    iban = models.TextField()
    tcuenta_id = models.ForeignKey(Tipocuenta,on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'cuenta'


class Movimientos(models.Model):
    cuenta_id = models.AutoField(db_column='Cuenta_id', primary_key=True, blank=True, null=False)  # Field name made lowercase.
    numcuenta = models.IntegerField(db_column='NumCuenta')  # Field name made lowercase.
    monto = models.IntegerField(db_column='Monto')  # Field name made lowercase.
    tipo_operacion = models.TextField(db_column='Tipo_Operacion')  # Field name made lowercase.
    hora = models.TextField(db_column='HORA')  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'Movimientos'

Sprint-8/homebanking/Prestamos/models.py
from django.db import models
from Clientes.models import Cliente
from Cuentas.models import Cuenta

# Create your models here.
class Prestamo(models.Model):
    loan_id = models.AutoField(primary_key=True)
    loan_type = models.TextField()
    loan_date = models.TextField()
    loan_total = models.IntegerField()
    customer_id = models.ForeignKey(Cliente,on_delete=models.CASCADE)
    account_num = models.ForeignKey(Cuenta,on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'prestamo'

Sprint-8/homebanking/Prestamos/views.py
####################################################################
#
#   Contiene al paquete PrestamosPackage
#       Metodos:
#           - log_page: Se encarga de renderizar la pagina 
#               a partir de la informacion en la base de datos.
#               Utiliza informacion de Prestamos y Cliente.
#
#           - mensaje: Se encarga de renderizar una pagina
#               que contiene la respuesta frente a la solicitud
#               de prestamo. Ante falla en ingreso, aqui se estipula
#               de donde proviene el error.
#
#           Los ingresos son autenticados!
#
#   Contiene las clases PrestamoView, que permite la visualizacion
#       de los prestamos existentes segun corresponda con el 
#       usuario logeado.
#       - Read-Only Viewset
#       - Requiere autenticacion
#
#   Contiene la clase PrestamoEmpleado, que permite la creacion y 
#       eliminacion de solicitudes de prestamo. La accion, tanto
#       de cancelacion como aceptacion efectua modificaciones 
#       sobre el saldo de la cuenta.
#       - Requiere de Autenticacion para Staff
#       - Permite modificacion de datos
#   
#####################################################################

from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from Clientes.models import Cliente, Tipoclientes
from Cuentas.models import Cuenta
from Prestamos.models import Prestamo
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.decorators import action
from Clientes.models  import *
from Cuentas.models   import *
from Tarjetas.models  import *
from Prestamos.models import *
from Api.serializers  import *

class PrestamoPackage:

    @login_required
    def log_page(request):
        
        user    = request.user
        prestamos = Prestamo.objects.filter(customer_id = user.id).order_by("-loan_date")
        cuenta = Cuenta.objects.filter(customer_id = user.id)
        content = {
            'prestamos':prestamos,
            'cuentas':cuenta
        }

        return render(request,"Prestamos/Prestamos.html",{'content':content})

    @login_required
    def mensaje(request):

        if request.method == 'POST':
            
            ################################
            # Parametros de Ingreso y de DB.
            user          = request.user
            
            cliente_tipo  = Cliente.objects.get(customer_id= user.id).id
            monto_maximo  = Tipoclientes.objects.get(tcliente_id = cliente_tipo).tcliente_limite_prestamo

            monto         = int(request.POST.get('Monto',0))
            tipo_prestamo = request.POST.get("seleccion_prestamo","")
            fecha         = request.POST.get("Fecha")
            cuenta        = request.POST.get("seleccion_cuenta","")

            ###############################
            # Checkeo parametros ingresados.
            opcion_prestamo = ["Hipotecario","Personal","Prendario"]
            opcion_prestamo_bool = tipo_prestamo in opcion_prestamo
            monto_zero_bool = monto > 0
            msg = ""

            if not opcion_prestamo_bool:
                msg = "Porfavor, seleccione el tipo de prestamo a tomar."
            
            elif not monto_zero_bool:
                msg = "Porfavor, ingrese un Monto a prestar mayor a cero."
            
            elif not cuenta.isnumeric():
                msg = "Ingrese el tipo de cuenta sobre la cual aplicar el prestamo."
            

            ################################
            # Checkeo segun tipo de cliente.
            if monto > monto_maximo:
                tcliente = Tipoclientes.objects.get(tcliente_id = cliente_tipo).tcliente_tipo
                msg = f"El monto solicitado supera al limite establecido para clientes {tcliente}."
                

            if msg == "":
                ###########################
                # Creacion de la solicitud.
                Prestamo.objects.create(
                    loan_type = tipo_prestamo,
                    loan_date = fecha,
                    loan_total = monto,
                    customer_id = user.id
                )

                ##################################
                # Update del balance de la cuenta.
                saldo_inicial = Cuenta.objects.get(account_id = int(cuenta)).balance
                Cuenta.objects.filter(account_id = cuenta).update(balance=saldo_inicial+monto)

                ######################################
                # Enviamos el mensaje correspondiente.
                msg = "Felicitaciones, su prestamo fue efectivamente consolidado."

            return render(request,'Prestamos/PrestamosStatus.html',{'msg':msg})   



class PrestamosView(viewsets.ReadOnlyModelViewSet):

    permission_classes = [permissions.IsAuthenticated]
    def get_queryset(self):

        is_staff = self.request.user.is_staff
        ##############################
        # Configuracion para Clientes.
        if not is_staff:
            user = self.request.user
            data = Prestamo.objects.filter(customer_id = user.id)
            return data
        
        ################################
        # Confirguracion para Empleados.
        elif is_staff:
                        
            branch_id = self.request.GET.get("Sucursal","")

            if branch_id != "":

                clientes = Cliente.objects.filter(branch_id=branch_id)
                clientes_id = [x.customer_id for x in clientes]
                
                prestamos = Prestamo.objects.filter(customer_id__in =clientes_id)
                return prestamos
            
            else:
                return Prestamo.objects.all()


    def get_serializer_class(self):
        
        is_staff = self.request.user.is_staff

        if is_staff:
            return PrestamoSerializerEmpleado

        else:
            return PrestamoClienteSerializer



class PrestamoEmpleado(viewsets.ModelViewSet):

    serializer_class = PrestamoSerializerEmpleado
    permission_classes = [permissions.IsAdminUser]
    queryset = Prestamo.objects.all()

    @action(detail=False,methods=['POST'])
    def add_Prestamo(self,request):

        monto = request.data.get("loan_total","")
        tipo_prestamo = request.data.get("loan_type","")
        fecha = request.data.get("loan_date")
        id = request.data.get("customer_id","")
        cuenta = request.data.get("account_num")
        cuenta_num = Cuenta.objects.get(account_id = cuenta)
        customer = Cliente.objects.get(customer_id = id)

        saldo_inicial = Cuenta.objects.get(account_id = cuenta).balance
        Cuenta.objects.filter(account_id = cuenta).update(balance=saldo_inicial+monto)
        Prestamo.objects.create(
            loan_type = tipo_prestamo,
            loan_date = fecha,
            customer_id = customer,
            loan_total = monto,
            account_num = cuenta_num
        )
        return Response(request.data,status.HTTP_200_OK)


    def delete(self,request):

        monto         = request.data.get("loan_total","")
        tipo_prestamo = request.data.get("loan_type","")
        fecha         = request.data.get("loan_date")
        id            = request.data.get("customer_id","")
        cuenta        = request.data.get("account_num","")
        saldo_inicial = Cuenta.objects.get(account_id = cuenta).balance
        Cuenta.objects.filter(account_id = cuenta).update(balance = saldo_inicial - monto)
        Prestamo.objects.filter(
            loan_type   = tipo_prestamo,
            loan_date   = fecha,
            loan_total  = monto,
            customer_id = id,
            account_num = cuenta
        ).delete()
        return Response(request.data,status.HTTP_200_OK)

Sprint-8/homebanking/Prestamos/templates/Prestamos/Prestamos.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Préstamos</title>
    <link href='https://css.gg/bell.css' rel='stylesheet'>
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
    crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BIZ+UDPGothic&display=swap" rel="stylesheet">     <title>ITBANK</title>
    <link rel="stylesheet" href="{% static 'Prestamos/css/Prestamos.css' %}">
</head>
<body>
    <header class="encabezado">
        <div class="logo">
          <a href="{% url 'cuenta' %}"><img class="img-logo" src="{% static 'Prestamos/img/Logo.png' %}" alt="ITBANK" /></a>
        </div>
        <div>
          <a href="{% url 'logout' %}"><button type="button" class="btn btn-dark border-2 rounded-circle"><i class="fa fa-sign-out"></i></button></a>
        </div>
    </header>
      <main>
            <div class="seccion">
              
              <main role="main">
                <div class="container">
                  <div class="row mt-3">
                    <div class="col-md-9 mx-auto mb-5">
                      <form action="Prestamos/Mensaje/" method="post" id="carform">{% csrf_token %}
                        <h3 class="mb-4">Solicitud de Prestamo</h3>
                        {{msg}}
                        <p>
                          <label for="prestamos"></label>
                          <select name="seleccion_prestamo" id="seleccion_prestamo" class="form-control" required>
                            <option value=" ">Seleccione el tipo de prestamo</option>
                            <option value="Hipotecario">Hipotecario</option>
                            <option value="Personal">Personal</option>
                            <option value="Prendario">Prendario</option>
                            
                          </select>
                          <label for="cuenta"></label>
                          <select name="seleccion_cuenta" id="seleccion_prestamo" class="form-control">
                            <option value=" ">Seleccione su Cuenta</option>
                            {% for accounts in content.cuentas %}
                                
                            var += <option  required value="{{accounts.account_id}}">{{accounts.account_id}}</option>
                            {% endfor %}
                            var      
                          </select>
                        </p>
                        <p>
                          <input type="number" name="Monto" required
                            id="id_monto" class="form-control" placeholder="Monto"/>
                        </p>
                        <p>
                          <input type="date" name="Fecha" required
                            id="Fecha" class="form-control" placeholder="Fecha de Inicio"/>
                        </p>
                        <p><input type="submit" class="btn btn-dark btn-block" value="Conceder Prestamo"></p>
                      </form>
                    </div>
                  </div>
                </div>
              </main>
            </div>

            <div class="seccion">
            <h2>Prestamos Conferidos</h2>
            <table class="table table-bordered">
              <tr>
                <th>Tipo de Prestamo</th>
                <th>Monto</th>
                <th>Fecha de Inicio</th>
              </tr>
              {% for prestamo in content.prestamos %}
              <tr>
                <td>{{prestamo.loan_type}}</td>
                <td>${{prestamo.loan_total}}</td>
                <td>{{prestamo.loan_date}}</td>
              </tr>
              {% endfor %}
            </table>
      </main>
</body>
</html>

Sprint-8/homebanking/Prestamos/templates/Prestamos/PrestamosStatus.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Prestamos/css/Prestamos.css' %}">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=BIZ+UDPGothic&display=swap" rel="stylesheet">     <title>ITBANK</title>
    <title>Préstamos</title>
</head>
<body>
    <header class="encabezado">
        <div class="logo">
          <a href="{% url 'cuenta' %}"><img class="img-logo" src="{% static 'Prestamos/img/Logo.png' %}" alt="ITBANK" /></a>
        </div>
        <div>
          <a href="{% url 'logout' %}"><button type="button" class="btn btn-dark border-2 rounded-circle"><i class="fa fa-sign-out"></i></button></a>
        </div>
      </header>
      <main>
            <div class="seccion">
              {{msg}}
              <a href="{% url 'prestamos' %}"><button class="btn btn-dark btn-block" type="button">Regresar</button></a>
            </div>

            
      </main>
</body>
</html>